CREATE SEQUENCE SEQ_IDPREDTRG
INCREMENT BY 1
START WITH 1
NOCYCLE
CACHE 10;

CREATE OR REPLACE TRIGGER PREDMETTRGOVINE_PK_TRIGGER
BEFORE INSERT
ON PREDMETTRGOVINE
FOR EACH ROW
BEGIN
 SELECT Seq_IDPREDTRG.NEXTVAL
 INTO :NEW.IDPREDTRG
 FROM SYS.DUAL;
END;

CREATE SEQUENCE SEQ_IDZAHTRG
INCREMENT BY 1
START WITH 1
NOCYCLE
CACHE 10;

CREATE OR REPLACE TRIGGER ZAHTEVZATRGOVINU_PK_TRIGGER
BEFORE INSERT
ON ZAHTEVZATRGOVINU
FOR EACH ROW
BEGIN
 SELECT Seq_IDZAHTRG.NEXTVAL
 INTO :NEW.IDZAHTRG
 FROM SYS.DUAL;
END;

CREATE SEQUENCE SEQ_IDTRG
INCREMENT BY 1
START WITH 1
NOCYCLE
CACHE 10;

CREATE OR REPLACE TRIGGER TRGOVINA_PK_TRIGGER
BEFORE INSERT
ON TRGOVINA
FOR EACH ROW
BEGIN
 SELECT Seq_IDTRG.NEXTVAL
 INTO :NEW.IDTRG
 FROM SYS.DUAL;
END;

CREATE OR REPLACE TRIGGER ZAHTEVZATRGOVINU_ACCEPT_TR
FOR UPDATE OF STATUSZAHTRG
ON ZAHTEVZATRGOVINU
COMPOUND TRIGGER

  TYPE ZahtIDTableType IS TABLE OF ZAHTEVZATRGOVINU.IDZAHTRG%TYPE;
  ZahtIDs ZahtIDTableType := ZahtIDTableType();

  BEFORE EACH ROW IS
  BEGIN
    IF :NEW.STATUSZAHTRG = 'ACCEPTED' THEN
      ZahtIDs.EXTEND;
      ZahtIDs(ZahtIDs.COUNT) := :OLD.IDZAHTRG;
    END IF;
  END BEFORE EACH ROW;

  AFTER STATEMENT IS
  BEGIN
    FOR i IN 1 .. ZahtIDs.COUNT LOOP
      FOR PREDMET IN (SELECT P.IDPREDTRG, P.TIPPREDTRG, P.IDPRAVA, P.IDIGRAC, P.IDZAHTRG, P.IDPIK
                      FROM PREDMETTRGOVINE P
                      WHERE P.IDZAHTRG = ZahtIDs(i)) LOOP

        FOR ZAHTEV IN (SELECT Z.IDZAHTRG
                       FROM ZAHTEVZATRGOVINU Z
                       JOIN PREDMETTRGOVINE P ON P.IDZAHTRG = Z.IDZAHTRG
                       WHERE Z.STATUSZAHTRG = 'IN_PROGRESS'
                         AND (P.IDIGRAC = PREDMET.IDIGRAC OR 
                              P.IDPIK = PREDMET.IDPIK OR 
                              P.IDPRAVA = PREDMET.IDPRAVA)) LOOP
            
          UPDATE ZAHTEVZATRGOVINU 
          SET STATUSZAHTRG = 'DECLINED', 
              RAZLOGODBIJ = 'Another trade proposal has been accepted'
          WHERE IDZAHTRG = ZAHTEV.IDZAHTRG;
        
        END LOOP;
      END LOOP;
    END LOOP;
  END AFTER STATEMENT;
END ZAHTEVZATRGOVINU_ACCEPT_TR;
